nodetype:
    ac: { L: 0.01, S: 50, Lp: 0, Sp: 0, max_cap: 1e5 }
    dc:
        L: 39.54 
        Lp: 98.79
        S: 0  # 101.1 - hvdc costs part of wind farm
        Sp: 0.01  # 564.69 - hvdc costs part of wind farm
        max_cap: 1e5
branchtype:
    ac:
        B: 5
        Bdp: 1.15
        Bd: 0.656
        CL: 1.562
        CLp: 0
        CS: 4.813
        CSp: 0
        max_cap: 400
        max_num: 5
        loss_fix: 0
        loss_slope: 5e-5
    dc:
        B: 3.344
        Bdp: 0.606  # after scale_Bd=5; original=1.216
        Bd: 1.525  # after scale_Bd=5; original=0.305
        CL: 6.59 # C = switchgear costs = 1/3 of converter (1/6 per endpoint)
        CLp: 16.465
        CS: 6.59
        CSp: 16.465
        max_cap: 2000
        max_num: 5
        loss_fix: 0
        loss_slope: 3e-5
    dummy:
        B: 0
        Bdp: 0
        Bd: 0
        CL: 0
        CLp: 0.1 # nonzero to limit capacity to what is necessary
        CS: 0
        CSp: 0.1 # nonzero to limit capacity to what is necessary
        max_cap: 100000
        max_num: 5
        loss_fix: 0
        loss_slope: 0
gentype:
    coal: {Cp: 0, CO2: 0, max_cap: 10000}      
    gas: {Cp: 0, CO2: 0, max_cap: 10000}
    oil: {Cp: 0, CO2: 0, max_cap: 10000}
    hydro: {Cp: 0, CO2: 0, max_cap: 10000}
    nuclear: {Cp: 0, CO2: 0, max_cap: 10000}
    solar: {Cp: 0, CO2: 0, max_cap: 10000}
    windon: {Cp: 0, CO2: 0, max_cap: 10000}
    res_other: {Cp: 0, CO2: 0, max_cap: 10000}
    nonres_other: {Cp: 0, CO2: 0, max_cap: 10000}
    windoff: {Cp: 0, CO2: 0, max_cap: 10000}
parameters:
    investment_years: [2035, 2040, 2050]
    finance_interest_rate: 0.05
    finance_years: 40
    operation_maintenance_rate: 0.05
    CO2_price: 0
    CO2_cap: null
    load_shed_penalty: 300 # very high value of lost load (loadshedding penalty)
    profiles_period_suffix: False # Use same profiles for all operating periods
    load_flex_shift_frac: {2035: 0.15, 2040: 0.25, 2050: 0.30}
    load_flex_shift_max: {2035: 2, 2040: 2, 2050: 2}
    load_flex_price_frac: {2035: 0, 2040: 0, 2050: 0} # no price-sensitive load
    load_flex_price_cap : {2035: 20, 2040: 20, 2050: 20}
