name: CI Build

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          #- 'ubuntu-latest'
          #- 'macos-latest'
          - "windows-latest"
        python-version:
          #- "3.9"
          - "3.10"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2

      - name: Setup Python
        uses: actions/setup-python@v4.1.0
        with:
          python-version: ${{matrix.python-version}}

      - uses: snok/install-poetry@v1.3.1
        with:
          virtualenvs-create: true

      - name: Check pyproject.toml validity
        run: poetry check --no-interaction

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v2.1.6
        with:
          path: ${{github.workspace}}/.venv
          key: ${{ matrix.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: ${{ matrix.os }}-

      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
      #- run: mpicc helloworld.c -o helloworld
      #- run: mpiexec -n 2 ./helloworld
      #- run: if ["$RUNNER_OS" == "Linux"]; then
      #          mpicc helloworld.c -o helloworld
      #          mpiexec -n 2 ./helloworld
      #       else

      - name: Install deps
        if: steps.cache-deps.cache-hit != 'true'
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction

      - name: Run tests
        run: poetry run pytest -v

      - name: Build artifacts
        run: poetry build
