name: CI tests incl. CBC solver

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: Build and test powergim
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Dockerfile
        run: docker pull haraldsvendsen/powergim
      - name: Test PowerGIM with CBC
        run: docker run --rm -w /code -v "$(pwd):/code" haraldsvendsen/powergim bash -c "poetry install && poetry run pytest"
